# Generated by Django 4.1.7 on 2023-03-15 14:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name_kanji', models.CharField(blank=True, max_length=35, null=True)),
                ('first_name_kanji', models.CharField(blank=True, max_length=35, null=True)),
                ('last_name_katakana', models.CharField(blank=True, max_length=35, null=True)),
                ('first_name_katakana', models.CharField(blank=True, max_length=35, null=True)),
                ('last_name_romaji', models.CharField(blank=True, max_length=35, null=True)),
                ('first_name_romaji', models.CharField(blank=True, max_length=35, null=True)),
                ('main_page_active', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
