# Generated by Django 4.1.7 on 2023-03-22 01:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0003_technicalskills_skill_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='technicalskills',
            name='skill_start',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='technicalskills',
            name='skill_type',
            field=models.IntegerField(choices=[(1, 'Languages'), (2, 'Frameworks'), (3, 'Databases'), (4, 'Tools')]),
        ),
    ]
