# Generated by Django 4.1.7 on 2023-03-23 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0004_technicalskills_skill_start_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=64)),
            ],
        ),
        migrations.AlterField(
            model_name='technicalskills',
            name='skill_title',
            field=models.CharField(max_length=64),
        ),
    ]
