# Generated by Django 4.1.7 on 2023-03-23 23:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0005_projects_alter_technicalskills_skill_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='project_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
