# Generated by Django 4.1.7 on 2023-03-24 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0006_projects_project_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='project_description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
