# Generated by Django 4.1.7 on 2023-03-26 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0007_projects_project_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='project_stub',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
    ]
