# Generated by Django 4.1.7 on 2023-04-03 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0011_projects_project_github_projects_project_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='project_github',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='projects',
            name='project_subtitle',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='projects',
            name='project_title',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='projects',
            name='project_website',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
