# Generated by Django 4.1.7 on 2023-04-04 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0012_alter_projects_project_github_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details_text', models.TextField()),
                ('details_image_url', models.CharField(max_length=512)),
                ('details_order', models.IntegerField()),
                ('related_project', models.ManyToManyField(to='mainpage.projects')),
            ],
        ),
    ]
