# Generated by Django 4.1.7 on 2023-04-14 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0014_projects_project_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='project_image_alt',
            field=models.CharField(default='', max_length=512),
            preserve_default=False,
        ),
    ]
