# Generated by Django 4.1.7 on 2023-04-17 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0015_projects_project_image_alt'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdetails',
            name='details_image_alt',
            field=models.CharField(default='', max_length=512),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectdetails',
            name='details_image_description',
            field=models.CharField(default='', max_length=2048),
            preserve_default=False,
        ),
    ]
