# Generated by Django 4.1.7 on 2023-04-17 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0016_projectdetails_details_image_alt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='project_technologies',
            field=models.ManyToManyField(to='mainpage.technicalskills'),
        ),
    ]
