# Generated by Django 4.1.7 on 2023-04-18 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0018_alter_projectdetails_details_image_alt_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectdetails',
            name='related_project',
        ),
        migrations.AddField(
            model_name='projectdetails',
            name='related_project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mainpage.projects'),
            preserve_default=False,
        ),
    ]
