# Generated by Django 4.1.7 on 2023-04-28 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0019_remove_projectdetails_related_project_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='project_subtitle',
            field=models.TextField(),
        ),
    ]
